version: 0.2
phases:
  install:
    commands:
      - echo updating ubuntu distro
      - apt-get update
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - echo Installing NPM...
      - npm -v
      - node -v
      #- apt-get install -y npm
      #- apt-get install -y build-essentials
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo nothing to build
      #- npm run build --prefix client/
artifacts:
  files:
    - "**/*"
    #- "client/build/**/*"
    #- "client/build/static/**/*"
    #- ".ebextensions/**/*"
  discard-paths: no
  #base-directory: 'client/build*'
eb_codebuild_settings:
  CodeBuildServiceRole: AWSElasticBeanstalkFullAccess
  ComputeType: BUILD_GENERAL1_SMALL
  Image: "aws/codebuild/standard:4.0"
  Timeout: 30